### ISSUE TITLE
大佬你好， DLUTModernWebvpnBrowser的证书过期了，无法安装了

### ISSUE THREAD

**Issue by johnzhang777** [IShiraiKurokoI/DLUTModernWebvpnBrowser#1]

**Comment by IShiraiKurokoI** [comment]
证书已更新，可以使用。新版本：https://github.com/IShiraiKurokoI/DLUTModernWebvpnBrowser/releases/tag/1.4.0.0 

另外其实也可以自己用visual studio生成并安装，这样就不需要安装我的证书了
